# isis_constants.py
# Holds all the definitions
# - INFO tiles
# - SPRITE tiles
# - etc

TILESIZE = 16.0

# Keen state constants
kON_GROUND = 0
kFALLING = 1
kON_POLE = 2
kON_LEDGE = 3
kIN_WATER = 4
kIN_DOOR = 5
kTELEPORT = 6
kDYING = 7
kSPEW = 8

# Sounds
SFX_W_BLOWGUN = 5
SFX_W_ZEFFER = 4
SFX_W_PULSAR = 3
SFX_W_SOLARIZER = 2
SFX_W_HR42 = 1
SFX_W_PLUTEZARP = 0
SFX_W_HARPOON = 6
SFX_W_RAYGUN = 7
SFX_W_NEURAL = 8
SFX_W_HITWALL = 9

SFX_ITEM_POINTS = 10
SFX_ITEM_WEAPON = 11
SFX_ITEM_WEAPON_NEURAL = 12
SFX_ITEM_KEY = 13
SFX_ITEM_KEY_USE = 14
SFX_ITEM_1UP = 15

SFX_KEEN_JUMP = 16
SFX_KEEN_POGO = 17
SFX_KEEN_BUBBLES = 18
SFX_KEEN_SPLASH = 19
SFX_KEEN_DIE = 20
SFX_KEEN_SWITCH = 21

SFX_ENEMY_DROPLET = 22
SFX_ENEMY_SLUG = 23
SFX_ENEMY_MINE = 24
SFX_ENEMY_SHOOT1 = 25
SFX_ENEMY_SHOOT2 = 26
SFX_ENEMY_SHOOT3 = 27
SFX_ENEMY_SHOOT4 = 28
SFX_ENEMY_SHOOT5 = 29

SFX_WX_RAIN = 30
SFX_WX_LIGHTNING = 31

SFX_LEVEL_START = 32
SFX_LEVEL_FINISH = 33

SFX_ITEM_INVENTORY = 34
SFX_ENEMY_FOOG_JUMP = 35
SFX_ENEMY_SPLAT = 36

# Items
# Point Items
ITEM_KEY_RED = 0
ITEM_KEY_YELLOW = 1
ITEM_KEY_GREEN = 2
ITEM_KEY_CYAN = 3
ITEM_KEY_BLUE = 4
ITEM_KEY_MAGENTA = 5
ITEM_JBEAN_RED = 6
ITEM_JBEAN_YELLOW = 7
ITEM_JBEAN_GREEN = 8
ITEM_JBEAN_CYAN = 9
ITEM_JBEAN_BLUE = 10
ITEM_JBEAN_PURPLE = 11
ITEM_COLA = 12
ITEM_BURGER = 13
ITEM_GINGER = 14
ITEM_SUGAR = 15
ITEM_CEREAL = 16

# Health Items
ITEM_PYAPA_FRUIT = 17
ITEM_PEETA_BERRIES = 18
ITEM_ISIS_FRUIT = 19
ITEM_NEPHTHYS_FRUIT = 20
ITEM_POTION = 21
ITEM_YORP = 22

# Powerups
ITEM_SHOES = 23
ITEM_POINTS = 24
ITEM_GOD = 25
ITEM_CRAZY = 26
ITEM_ANTI = 27
ITEM_REGEN = 28
ITEM_DEGEN = 29

# Inventory
ITEM_BATTERY = 39
ITEM_SHIELD = 40
ITEM_IONSCANNER = 41
ITEM_UNKNOWN = 42

# Weapons
ITEM_BLOWGUN = 30
ITEM_ZEFFER = 31
ITEM_PULSAR = 32
ITEM_SOLARIZER = 33
ITEM_HR42 = 34
ITEM_PLUTEZARP = 35
ITEM_HARPOON = 36
ITEM_RAYGUN = 37
ITEM_NEURAL = 38

# Doors
DOOR_STATE_CLOSED = 0
DOOR_STATE_OPEN = 1
DOOR_STATE_FINISHED = 2
DOOR_OPEN_SPEED = 50


# Number of playing tiles (this is needed to offset the INFO ID numbers)
MAXTILES = 6784 #5760 #4736
MAXINFO = 144

#_______________________________________________________________________
# Information Tile IDs
INFO_SOLID = MAXTILES + 2
INFO_SOLID_FROM_TOP = MAXTILES + 3
INFO_SOLID_FROM_BOTTOM = MAXTILES + 4
INFO_SOLID_FROM_RIGHT = MAXTILES + 5
INFO_SOLID_FROM_LEFT = MAXTILES + 6
INFO_SOLID_NO_GRAB = MAXTILES + 7

INFO_UP_RIGHT_45 = MAXTILES + 18
INFO_DOWN_RIGHT_45 = MAXTILES + 19
INFO_UP_RIGHT_30_1 = MAXTILES + 20
INFO_UP_RIGHT_30_2 = MAXTILES + 21
INFO_DOWN_RIGHT_30_1 = MAXTILES + 22
INFO_DOWN_RIGHT_30_2 = MAXTILES + 23
INFO_POLE = MAXTILES + 25

INFO_UP_RIGHT_45w = MAXTILES + 50
INFO_DOWN_RIGHT_45w = MAXTILES + 51
INFO_UP_RIGHT_30_1w = MAXTILES + 52
INFO_UP_RIGHT_30_2w = MAXTILES + 53
INFO_DOWN_RIGHT_30_1w = MAXTILES + 54
INFO_DOWN_RIGHT_30_2w = MAXTILES + 55
INFO_ENEMY_SOLIDw = MAXTILES + 66

INFO_ENEMY_SOLID = MAXTILES + 34
INFO_ENEMY_LEFT = MAXTILES + 35
INFO_ENEMY_RIGHT = MAXTILES + 36
INFO_ENEMY_TELE = MAXTILES + 37

INFO_WATER = MAXTILES + 82
INFO_DOOR_1 = MAXTILES + 97
INFO_TELE_1 = MAXTILES + 113
INFO_EXIT_1 = MAXTILES + 129

INFO_HURT_1 = MAXTILES + 68
INFO_HURT_2 = MAXTILES + 69
INFO_HURT_5 = MAXTILES + 70
INFO_DIE = MAXTILES + 71

INFO_HURT_1w = MAXTILES + 84
INFO_HURT_2w = MAXTILES + 85
INFO_HURT_5w = MAXTILES + 86
INFO_DIEw = MAXTILES + 87

INFO_PLATFORM_UP = MAXTILES + 41
INFO_PLATFORM_DOWN = MAXTILES + 42
INFO_PLATFORM_RIGHT = MAXTILES + 43
INFO_PLATFORM_LEFT = MAXTILES + 44
INFO_PLATFORM_UP_RIGHT = MAXTILES + 45
INFO_PLATFORM_DOWN_LEFT = MAXTILES + 46
INFO_PLATFORM_UP_LEFT = MAXTILES + 47
INFO_PLATFORM_DOWN_RIGHT = MAXTILES + 48

INFO_PLATFORM_1 = MAXTILES + 73
INFO_PLATFORM_8 = MAXTILES + 80
#_______________________________________________________________________
# Sprites
# Sprite tile definitions
SPRITESTART = MAXTILES + MAXINFO

SPRITE_CHECKPOINT = SPRITESTART + 50

SPRITE_KEEN_RIGHT = SPRITESTART + 1
SPRITE_KEEN_LEFT = SPRITESTART + 2
SPRITE_KEEN_RIGHT_WATER = SPRITESTART + 3
SPRITE_KEEN_LEFT_WATER = SPRITESTART + 4
SPRITE_EGA = SPRITESTART + 5
SPRITE_HEALTH1 = SPRITESTART + 6
SPRITE_HEALTH2 = SPRITESTART + 7
SPRITE_HEALTH5 = SPRITESTART + 8

SPRITE_BG = SPRITESTART + 20
SPRITE_MUSIC = SPRITESTART + 39

SPRITE_NIGHT = SPRITESTART + 191
SPRITE_RAIN = SPRITESTART + 210
SPRITE_SNOW = SPRITESTART + 211
SPRITE_CLOUD = SPRITESTART + 212
SPRITE_LIGHTNING = SPRITESTART + 213

SPRITE_KEY_RED = SPRITESTART + 14
SPRITE_KEY_YELLOW = SPRITESTART + 15
SPRITE_KEY_GREEN = SPRITESTART + 16
SPRITE_KEY_CYAN = SPRITESTART + 17
SPRITE_KEY_BLUE = SPRITESTART + 18
SPRITE_KEY_MAGENTA = SPRITESTART + 19

SPRITE_DOOR_RED = SPRITESTART + 33
SPRITE_DOOR_YELLOW = SPRITESTART + 34
SPRITE_DOOR_GREEN = SPRITESTART + 35
SPRITE_DOOR_CYAN = SPRITESTART + 36
SPRITE_DOOR_BLUE = SPRITESTART + 37
SPRITE_DOOR_MAGENTA = SPRITESTART + 38

SPRITE_PLATFORM_1 = SPRITESTART + 216
SPRITE_PLATFORM_2 = SPRITESTART + 217
SPRITE_PLATFORM_3 = SPRITESTART + 218
SPRITE_SWITCH_1 =  SPRITESTART + 198
SPRITE_SWITCH_2 =  SPRITESTART + 199
SPRITE_SWITCH_3 =  SPRITESTART + 200

SPRITE_JBEAN_RED = SPRITESTART + 71
SPRITE_JBEAN_YELLOW = SPRITESTART + 72
SPRITE_JBEAN_GREEN = SPRITESTART + 73
SPRITE_JBEAN_CYAN = SPRITESTART + 74
SPRITE_JBEAN_BLUE = SPRITESTART + 75
SPRITE_JBEAN_PURPLE = SPRITESTART + 76

SPRITE_COLA = SPRITESTART + 91
SPRITE_BURGER = SPRITESTART + 92
SPRITE_GINGER = SPRITESTART + 93
SPRITE_SUGAR = SPRITESTART + 94
SPRITE_CEREAL = SPRITESTART + 95

SPRITE_PYAPA_FRUIT = SPRITESTART + 128
SPRITE_PEETA_BERRIES = SPRITESTART + 129
SPRITE_ISIS_FRUIT = SPRITESTART + 130
SPRITE_NEPHTHYS_FRUIT = SPRITESTART + 131
SPRITE_POTION = SPRITESTART + 132
SPRITE_YORP = SPRITESTART + 133

SPRITE_SHOES = SPRITESTART + 184
SPRITE_POINTS = SPRITESTART + 185
SPRITE_GOD = SPRITESTART + 186
SPRITE_CRAZY = SPRITESTART + 187
SPRITE_ANTI = SPRITESTART + 188
SPRITE_REGEN = SPRITESTART + 189
SPRITE_DEGEN = SPRITESTART + 190

SPRITE_BATTERY = SPRITESTART + 168
SPRITE_SHIELD = SPRITESTART + 169
SPRITE_IONSCANNER = SPRITESTART + 170
SPRITE_UNKNOWN = SPRITESTART + 171

SPRITE_BLOWGUN = SPRITESTART + 220
SPRITE_ZEFFER = SPRITESTART + 221
SPRITE_PULSAR = SPRITESTART + 222
SPRITE_SOLARIZER = SPRITESTART + 223
SPRITE_HR42 = SPRITESTART + 224
SPRITE_PLUTEZARP = SPRITESTART + 225
SPRITE_HARPOON = SPRITESTART + 226
SPRITE_RAYGUN = SPRITESTART + 227
SPRITE_NEURAL = SPRITESTART + 228

# Drops
SPRITE_WATER_DROP = SPRITESTART + 196
SPRITE_ACID_DROP = SPRITESTART + 197

# Enemies (Jungle & Cave dwelling)
SPRITE_FOOG = SPRITESTART + 77
SPRITE_FOOGJUMP = SPRITESTART + 78
SPRITE_SPIDER = SPRITESTART + 79
SPRITE_FROG_WALK = SPRITESTART + 80
SPRITE_FROG_SWIM = SPRITESTART + 81
SPRITE_HOLEMONSTER = SPRITESTART + 82
SPRITE_BLUEMOUTH = SPRITESTART + 83
SPRITE_GARNAK = SPRITESTART + 84
SPRITE_YELLOW = SPRITESTART + 85
SPRITE_DEMON = SPRITESTART + 86
SPRITE_PLANTGUY = SPRITESTART + 87

# Enemies (Water & Breakable Rocks)
SPRITE_REDFISH = SPRITESTART + 96
SPRITE_CHOMPERFISH = SPRITESTART + 97
SPRITE_URCHIN = SPRITESTART + 98
SPRITE_FLOPPY = SPRITESTART + 99
SPRITE_YELLOWFISH = SPRITESTART + 100
SPRITE_GREENFISH = SPRITESTART + 101
SPRITE_BLUEFISH = SPRITESTART + 102
SPRITE_ROCK_GREY = SPRITESTART + 103
SPRITE_ROCK_MOSS = SPRITESTART + 104
SPRITE_ROCK_BROWN = SPRITESTART + 105
SPRITE_MINE = SPRITESTART + 106

# Enemies (Soldiers & Robots)
SPRITE_RAT = SPRITESTART + 115
SPRITE_LEMMING = SPRITESTART + 116
SPRITE_TRUCKGUY1 = SPRITESTART + 117
SPRITE_TRUCKGUY2 = SPRITESTART + 118
SPRITE_TRUCKGUY1_WALK = SPRITESTART + 119
SPRITE_TRUCKGUY2_WALK = SPRITESTART + 120
SPRITE_ROBOT_GREY = SPRITESTART + 121
SPRITE_ROBOT_RED = SPRITESTART + 122
SPRITE_ROBOT_FLASHER = SPRITESTART + 123
SPRITE_ROBOT_HOVER = SPRITESTART + 124
SPRITE_TELETURRET = SPRITESTART + 125

# Enemies (Garden & Bosses)
SPRITE_CATERPILLAR = SPRITESTART + 134
SPRITE_SNAIL = SPRITESTART + 135
SPRITE_BIGFROG = SPRITESTART + 136
SPRITE_DRAGONFLY = SPRITESTART + 137
SPRITE_BIRD = SPRITESTART + 138
SPRITE_FOOG_WARRIOR = SPRITESTART + 139
SPRITE_ROBO_GREY = SPRITESTART + 140
SPRITE_ROBO_BLUE = SPRITESTART + 141
SPRITE_SHAPESHIFTER = SPRITESTART + 142
SPRITE_EVILKEEN = SPRITESTART + 143

# Enemies (Isonians & Secret Level)
SPRITE_ISONIAN_GREEN = SPRITESTART + 153
SPRITE_ISONIAN_RED = SPRITESTART + 154
SPRITE_ISONIAN_WHITE = SPRITESTART + 155
SPRITE_ISONIAN_FLY = SPRITESTART + 156
SPRITE_ISONIAN_GIANT1 = SPRITESTART + 157
SPRITE_ISONIAN_GIANT2 = SPRITESTART + 158
SPRITE_DEVIL = SPRITESTART + 159
SPRITE_YORPY = SPRITESTART + 160
SPRITE_GARG = SPRITESTART + 161
SPRITE_SLUG = SPRITESTART + 162
